
import React, { useState, useEffect } from 'react';
import { 
  LayoutDashboard, 
  DollarSign, 
  PlusCircle, 
  LogOut, 
  Trash2, 
  Lock, 
  Layers, 
  CheckCircle, 
  Globe, 
  AlertTriangle, 
  Zap, 
  Loader2, 
  Settings,
  Save,
  RefreshCw,
  Copy,
  ExternalLink,
  Database,
  ArrowRight,
  DatabaseZap,
  ShieldCheck,
  Terminal,
  FileCode,
  TrendingUp
} from 'lucide-react';
import { ARTICLES } from '../constants';
import { Category, Article } from '../types';
import { db } from '../supabaseService';
import SEO from '../components/SEO';

const AdminDashboard = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(() => sessionStorage.getItem('ayyan_admin_auth') === 'true');
  const [key, setKey] = useState('');
  const [activeTab, setActiveTab] = useState<'overview' | 'articles' | 'sales' | 'settings'>('overview');
  
  const [allArticles, setAllArticles] = useState<Article[]>([]);
  const [sales, setSales] = useState<any[]>([]);
  const [isSyncing, setIsSyncing] = useState(false);
  const [dbStatus, setDbStatus] = useState<'online' | 'offline' | 'checking'>('checking');
  
  const [manualUrl, setManualUrl] = useState('');
  const [manualKey, setManualKey] = useState('');
  const [testResult, setTestResult] = useState<{success?: boolean, message: string} | null>(null);

  const [newArticle, setNewArticle] = useState({
    title: '', excerpt: '', introText: '', content: '',
    category: Category.Serverless, price: 45, image: '', isPLR: true
  });

  const loadData = async () => {
    setIsSyncing(true);
    setDbStatus('checking');
    
    // Fetch from Cloud
    const [cloudArticles, cloudSales] = await Promise.all([
      db.getAllArticles(),
      db.getAllSales()
    ]);
    
    const isOk = db.isConfigured();
    setDbStatus(isOk ? 'online' : 'offline');
    setAllArticles([...ARTICLES, ...cloudArticles]);
    setSales(cloudSales);
    setIsSyncing(false);
  }

  useEffect(() => { loadData(); }, []);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (key === 'admin123') {
      setIsLoggedIn(true);
      sessionStorage.setItem('ayyan_admin_auth', 'true');
    } else { alert('Access Denied.'); }
  };

  const handleTestConnection = async () => {
    setTestResult({ message: 'Running diagnostic...' });
    const res = await db.testConnection();
    setTestResult(res);
  };

  const handleSaveCredentials = (e: React.FormEvent) => {
    e.preventDefault();
    db.setManualCredentials(manualUrl, manualKey);
  };

  const handleAddArticle = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!db.isConfigured()) {
      alert("Database not connected.");
      setActiveTab('settings');
      return;
    }

    setIsSyncing(true);
    const id = `art-${Date.now()}`;
    const articleToSave: Article = { 
      ...newArticle, id, 
      date: new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }),
      readTime: `${Math.max(3, Math.ceil(newArticle.content.split(' ').length / 200))} min`
    };
    
    const result = await db.saveArticle(articleToSave);
    if (result.success) {
      alert('SUCCESS: Your article is now live in the cloud!');
      setNewArticle({ title: '', excerpt: '', introText: '', content: '', category: Category.Serverless, price: 45, image: '', isPLR: true });
      loadData();
    } else {
      alert(`ERROR: ${result.error}`);
    }
    setIsSyncing(false);
  };

  const deleteArticle = async (id: string) => {
    if (confirm('Delete from cloud?')) {
      setIsSyncing(true);
      await db.deleteArticle(id);
      loadData();
      setIsSyncing(false);
    }
  };

  const masterSql = `-- 1. ARTICLES TABLE
CREATE TABLE IF NOT EXISTS articles (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  excerpt TEXT,
  "introText" TEXT,
  content TEXT,
  category TEXT,
  date TEXT,
  "readTime" TEXT,
  image TEXT,
  price NUMERIC,
  "isPLR" BOOLEAN DEFAULT true,
  owner_id UUID DEFAULT auth.uid()
);

-- 2. SALES TABLE (FOR CLOUD STORAGE)
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  article_id TEXT,
  order_id TEXT,
  item_name TEXT,
  amount NUMERIC
);

-- 3. ENABLE SECURITY
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

-- 4. POLICIES
CREATE POLICY "Public Read" ON articles FOR SELECT USING (true);
CREATE POLICY "Admin Manage" ON articles FOR ALL USING (true);
CREATE POLICY "Public Read Sales" ON sales FOR SELECT USING (true);
CREATE POLICY "Admin Manage Sales" ON sales FOR ALL USING (true);

-- 5. REFRESH CACHE
NOTIFY pgrst, 'reload schema';`;

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    alert('SQL copied! Run this in Supabase to sync your Cloud Database.');
  };

  if (!isLoggedIn) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center px-4">
        <SEO title="Admin Login" description="Restricted access." />
        <div className="max-w-md w-full bg-white rounded-[2.5rem] p-10 shadow-xl border border-slate-200">
          <div className="flex justify-center mb-8">
            <div className="w-16 h-16 bg-slate-900 text-white rounded-2xl flex items-center justify-center shadow-lg"><Lock size={32} /></div>
          </div>
          <h1 className="text-2xl font-black text-center text-slate-900 mb-6 uppercase tracking-tighter">Ayyan Admin</h1>
          <form onSubmit={handleLogin} className="space-y-4">
            <input type="password" value={key} onChange={(e) => setKey(e.target.value)} className="w-full px-5 py-4 bg-slate-50 border border-slate-200 rounded-2xl text-center font-mono tracking-widest outline-none focus:ring-2 focus:ring-blue-500 transition-all" placeholder="Enter Admin Key" />
            <button type="submit" className="w-full py-5 bg-blue-600 text-white rounded-2xl font-bold hover:bg-blue-700 transition-all shadow-xl shadow-blue-100">Verify Identity</button>
          </form>
        </div>
      </div>
    );
  }

  const totalRevenue = sales.reduce((acc, sale) => acc + (Number(sale.amount) || 0), 0);

  return (
    <div className="min-h-screen bg-slate-50 flex">
      <aside className="w-72 bg-slate-900 text-white flex flex-col p-8 hidden lg:flex border-r border-slate-800 shrink-0 sticky top-0 h-screen">
        <div className="mb-12"><h2 className="text-2xl font-black tracking-tighter gradient-text">AYYAN.TECH</h2></div>
        <nav className="space-y-3 flex-grow">
          <button onClick={() => setActiveTab('overview')} className={`w-full flex items-center gap-4 px-5 py-4 rounded-2xl text-sm font-bold transition-all ${activeTab === 'overview' ? 'bg-blue-600 shadow-lg shadow-blue-900/50' : 'text-slate-400 hover:text-white hover:bg-slate-800'}`}><LayoutDashboard size={18} /> Dashboard</button>
          <button onClick={() => setActiveTab('articles')} className={`w-full flex items-center gap-4 px-5 py-4 rounded-2xl text-sm font-bold transition-all ${activeTab === 'articles' ? 'bg-blue-600 shadow-lg shadow-blue-900/50' : 'text-slate-400 hover:text-white hover:bg-slate-800'}`}><PlusCircle size={18} /> Manage Content</button>
          <button onClick={() => setActiveTab('sales')} className={`w-full flex items-center gap-4 px-5 py-4 rounded-2xl text-sm font-bold transition-all ${activeTab === 'sales' ? 'bg-blue-600 shadow-lg shadow-blue-900/50' : 'text-slate-400 hover:text-white hover:bg-slate-800'}`}><TrendingUp size={18} /> Sales & Analytics</button>
          <button onClick={() => setActiveTab('settings')} className={`w-full flex items-center gap-4 px-5 py-4 rounded-2xl text-sm font-bold transition-all ${activeTab === 'settings' ? 'bg-blue-600 shadow-lg shadow-blue-900/50' : 'text-slate-400 hover:text-white hover:bg-slate-800'}`}><Settings size={18} /> DB Config</button>
        </nav>
        <button onClick={() => { sessionStorage.clear(); window.location.reload(); }} className="flex items-center gap-4 px-5 py-4 rounded-2xl text-sm font-bold text-slate-500 hover:text-red-400 transition-colors mt-auto"><LogOut size={18} /> Sign Out</button>
      </aside>

      <main className="flex-grow p-8 lg:p-12 overflow-y-auto">
        <div className="max-w-6xl mx-auto space-y-12">
          
          {activeTab === 'overview' && (
            <>
              <header className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4">
                <div>
                  <h1 className="text-4xl font-black text-slate-900 tracking-tight">Overview</h1>
                  <p className="text-slate-500 font-medium">Cloud sync performance and connectivity.</p>
                </div>
                <div className={`flex items-center gap-3 px-5 py-2.5 rounded-2xl text-xs font-black uppercase tracking-widest border ${dbStatus === 'online' ? 'bg-emerald-50 text-emerald-600 border-emerald-100' : 'bg-red-50 text-red-600 border-red-100'}`}>
                  <div className={`w-2 h-2 rounded-full ${dbStatus === 'online' ? 'bg-emerald-500 animate-pulse' : 'bg-red-500'}`}></div>
                  {dbStatus === 'online' ? 'Cloud Sync Online' : 'Cloud Offline'}
                </div>
              </header>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div className="bg-white p-8 rounded-[2.5rem] shadow-sm border border-slate-100">
                  <div className="w-14 h-14 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center mb-6"><DollarSign size={28} /></div>
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Lifetime Revenue</p>
                  <h3 className="text-4xl font-black text-slate-900">${totalRevenue.toFixed(2)}</h3>
                </div>
                <div className="bg-white p-8 rounded-[2.5rem] shadow-sm border border-slate-100">
                  <div className="w-14 h-14 bg-emerald-50 text-emerald-600 rounded-2xl flex items-center justify-center mb-6"><CheckCircle size={28} /></div>
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Total Orders</p>
                  <h3 className="text-4xl font-black text-slate-900">{sales.length}</h3>
                </div>
                <div className="bg-white p-8 rounded-[2.5rem] shadow-sm border border-slate-100">
                  <div className="w-14 h-14 bg-orange-50 text-orange-600 rounded-2xl flex items-center justify-center mb-6"><Layers size={28} /></div>
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Cloud Content</p>
                  <h3 className="text-4xl font-black text-slate-900">{allArticles.length}</h3>
                </div>
              </div>
            </>
          )}

          {activeTab === 'settings' && (
            <div className="space-y-10">
               <header>
                 <h1 className="text-4xl font-black text-slate-900 tracking-tight">Cloud Link</h1>
                 <p className="text-slate-500 font-medium">Connect Supabase to move beyond local storage.</p>
               </header>

               <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
                  <div className="bg-white p-10 rounded-[2.5rem] border border-slate-100 shadow-sm space-y-8">
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 bg-blue-600 text-white rounded-xl flex items-center justify-center font-black">1</div>
                      <h3 className="text-xl font-bold text-slate-900">Credentials</h3>
                    </div>
                    
                    <form onSubmit={handleSaveCredentials} className="space-y-6">
                      <input value={manualUrl} onChange={e => setManualUrl(e.target.value)} required placeholder="https://xxx.supabase.co" className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none font-mono text-xs" />
                      <input value={manualKey} onChange={e => setManualKey(e.target.value)} required type="password" placeholder="Supabase Anon Key..." className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none font-mono text-xs" />
                      <div className="flex gap-4">
                        <button type="submit" className="flex-grow py-5 bg-blue-600 text-white rounded-2xl font-black hover:bg-blue-700 transition-all flex items-center justify-center gap-3">
                          <Save size={20} /> Enable Cloud Storage
                        </button>
                      </div>
                    </form>

                    <button onClick={handleTestConnection} className="w-full py-4 bg-white border border-slate-200 text-slate-900 rounded-xl font-black text-xs hover:bg-slate-50 transition-all flex items-center justify-center gap-3 shadow-sm uppercase tracking-widest">
                        <RefreshCw size={16} /> Run Diagnostics
                    </button>
                    {testResult && (
                        <div className={`p-4 rounded-xl text-xs font-bold border flex items-center gap-3 ${testResult.success ? 'bg-emerald-50 text-emerald-700 border-emerald-100' : 'bg-red-50 text-red-700 border-red-100'}`}>
                          {testResult.success ? <CheckCircle size={16} /> : <AlertTriangle size={16} />}
                          {testResult.message}
                        </div>
                    )}
                  </div>

                  <div className="bg-slate-900 text-white p-10 rounded-[2.5rem] shadow-2xl space-y-8">
                    <div className="flex items-center gap-4 relative z-10">
                      <div className="w-10 h-10 bg-blue-600 text-white rounded-xl flex items-center justify-center font-black">2</div>
                      <h3 className="text-xl font-bold text-blue-400">Initialize Tables</h3>
                    </div>

                    <div className="space-y-6">
                      <div className="p-5 bg-slate-800/50 border border-slate-700 rounded-2xl">
                        <p className="text-xs font-black uppercase text-blue-400 mb-2 tracking-widest flex items-center gap-2">
                          <Terminal size={14} /> Master Sync Script
                        </p>
                        <p className="text-slate-400 text-[11px] mb-4">Creates both <b>articles</b> and <b>sales</b> tables for full cloud functionality.</p>
                        <button onClick={() => copyToClipboard(masterSql)} className="w-full py-3 bg-blue-600 text-white rounded-xl font-black text-[10px] uppercase hover:bg-blue-700 transition-all flex items-center justify-center gap-2">
                          <Copy size={12} /> Copy Cloud Script
                        </button>
                      </div>

                      <div className="p-5 bg-slate-800/30 border border-slate-700/50 rounded-2xl">
                        <p className="text-xs font-black uppercase text-slate-500 mb-4 tracking-widest flex items-center gap-2">
                          <FileCode size={14} /> Cloud Schema
                        </p>
                        <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-[10px] font-mono text-slate-400">
                           <span>articles (table)</span><span>sales (table)</span>
                           <span>owner_id (uuid)</span><span>order_id (text)</span>
                        </div>
                      </div>
                    </div>
                  </div>
               </div>
            </div>
          )}

          {activeTab === 'articles' && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
              <div className="lg:col-span-2">
                <div className="bg-white p-10 rounded-[2.5rem] border border-slate-100 shadow-sm">
                  <h3 className="text-2xl font-black mb-8 flex items-center gap-4"><Zap className="text-blue-600" /> Cloud Publication</h3>
                  <form onSubmit={handleAddArticle} className="space-y-6">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <input required className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none" value={newArticle.title} onChange={e => setNewArticle({...newArticle, title: e.target.value})} placeholder="Title" />
                      <select className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none font-bold" value={newArticle.category} onChange={e => setNewArticle({...newArticle, category: e.target.value as any})}>
                        {Object.values(Category).map(c => <option key={c} value={c}>{c}</option>)}
                      </select>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <input type="number" className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none" value={newArticle.price} onChange={e => setNewArticle({...newArticle, price: Number(e.target.value)})} placeholder="Price" />
                      <input required className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none" value={newArticle.image} onChange={e => setNewArticle({...newArticle, image: e.target.value})} placeholder="Image URL" />
                    </div>
                    <textarea rows={2} required className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none text-sm" value={newArticle.excerpt} onChange={e => setNewArticle({...newArticle, excerpt: e.target.value})} placeholder="Excerpt" />
                    <input className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-2xl outline-none text-sm" value={newArticle.introText} onChange={e => setNewArticle({...newArticle, introText: e.target.value})} placeholder="Key Insight" />
                    <textarea rows={10} required className="w-full px-8 py-6 bg-slate-50 border border-slate-100 rounded-3xl outline-none font-mono text-sm leading-relaxed" value={newArticle.content} onChange={e => setNewArticle({...newArticle, content: e.target.value})} placeholder="Content" />
                    <button type="submit" disabled={isSyncing} className={`w-full py-5 text-white rounded-2xl font-black flex items-center justify-center gap-3 shadow-2xl transition-all ${dbStatus === 'online' ? 'bg-blue-600 hover:bg-blue-700' : 'bg-slate-400 cursor-not-allowed'}`}>
                      {isSyncing ? <Loader2 className="animate-spin" /> : <Globe size={20} />} 
                      {dbStatus === 'online' ? 'Sync to Cloud' : 'Connect DB'}
                    </button>
                  </form>
                </div>
              </div>

              <div className="space-y-4">
                <h3 className="font-black text-slate-400 uppercase text-xs tracking-widest px-4">Cloud Inventory</h3>
                {allArticles.slice().reverse().map((a: Article) => (
                    <div key={a.id} className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm flex items-center gap-4">
                      <img src={a.image} className="w-10 h-10 rounded-lg object-cover" alt="" />
                      <div className="flex-grow">
                        <p className="font-bold text-slate-900 text-xs line-clamp-1">{a.title}</p>
                        <p className="text-[9px] text-blue-600 font-black uppercase">{a.category}</p>
                      </div>
                      {!ARTICLES.find(sa => sa.id === a.id) && (
                        <button onClick={() => deleteArticle(a.id)} className="p-2 text-slate-300 hover:text-red-500 transition-all"><Trash2 size={16} /></button>
                      )}
                    </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'sales' && (
            <div className="bg-white p-12 rounded-[3rem] border border-slate-100 shadow-sm">
               <h3 className="text-3xl font-black text-slate-900 mb-8">Cloud Sales History</h3>
               <div className="overflow-x-auto">
                 <table className="w-full text-left">
                   <thead>
                     <tr className="border-b border-slate-100 text-[10px] font-black text-slate-400 uppercase tracking-widest">
                       <th className="pb-6">Date</th>
                       <th className="pb-6">Article</th>
                       <th className="pb-6">Order ID</th>
                       <th className="pb-6 text-right">Revenue</th>
                     </tr>
                   </thead>
                   <tbody>
                     {sales.length > 0 ? sales.map((sale, i) => (
                       <tr key={i} className="border-b border-slate-50 last:border-0">
                         <td className="py-6 text-slate-500 font-medium">{new Date(sale.created_at).toLocaleDateString()}</td>
                         <td className="py-6 font-bold text-slate-900">{sale.item_name}</td>
                         <td className="py-6 font-mono text-[10px] text-slate-400">{sale.order_id}</td>
                         <td className="py-6 font-black text-emerald-600 text-right">+${Number(sale.amount).toFixed(2)}</td>
                       </tr>
                     )) : (
                       <tr><td colSpan={4} className="py-20 text-center text-slate-400">No cloud sales yet.</td></tr>
                     )}
                   </tbody>
                 </table>
               </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default AdminDashboard;
